apiVersion: v1
kind: pod 
metadata: 
  name: my-pod
spec: 
  containers: 
    - name: my-c
      image: nginx
      ports: 
        - containerport: 80
      volumeMounts:
        -mountPath: /mnt
         name: new-vol
  volumes: 
    - name: new-vol
      persistenVolumeClaim: 
        claimName: my-pvc          