apiVersion: v1
kind: PersistenVolume
metadata:   
  name: my-pv 
spec:
  storageClassname: ""
  capacity: 
    storage: 5Gi
  volumeMode:  Filesystem
  accessModes: 
   - ReadWriteOnce: 
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeselectorTerm: 
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [controlplane]}